<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_checkbox_Music</name>
   <tag></tag>
   <elementGuidId>a8c89c61-0b87-472d-89bf-ac8044687393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>label[for='hobbies-checkbox-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label[for='hobbies-checkbox-3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
